/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiRevisionRouteImport } from './routes/api/revision'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevisionRoute = ApiRevisionRouteImport.update({
  id: '/api/revision',
  path: '/api/revision',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/revision': typeof RevisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/revision': typeof ApiRevisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/revision': typeof RevisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/revision': typeof ApiRevisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/revision': typeof RevisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/revision': typeof ApiRevisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/revision' | '/api/chat' | '/api/revision'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/revision' | '/api/chat' | '/api/revision'
  id: '__root__' | '/' | '/revision' | '/api/chat' | '/api/revision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RevisionRoute: typeof RevisionRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiRevisionRoute: typeof ApiRevisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revision': {
      id: '/api/revision'
      path: '/api/revision'
      fullPath: '/api/revision'
      preLoaderRoute: typeof ApiRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RevisionRoute: RevisionRoute,
  ApiChatRoute: ApiChatRoute,
  ApiRevisionRoute: ApiRevisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
